#该参数是用来开启重试机制
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
        
        
#断路器的超时时间需要大于Ribbon的超时时间，不然不会触发重试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

sundata-provider:
  ribbon:
    ConnectTimeout: 250                         #请求你连接的超时时间
    ReadTimeout: 1000                           #请求处理的超时时间
    OkToRetryOnAllOperations: true              #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2                 #切换实例的重试次数
    MaxAutoRetries: 1                           #对当前实例的重试次数
